### ISSUE TITLE
Setting up mailsac/config.js help.

### ISSUE THREAD

**Issue by tdcaseware** [ruffrey/mailsac#20]
Can anyone help me with setting up mailsac in linux(centOS)??? The instructions are just not clear.

What does "just update the config.js" mean? Do I have to create a database in mongo first? Could anyone possibly post your example config file or provide a small tutorial to get me started on it.

**Comment by ruffrey** [comment]
Being unfamiliar with centos, take my instructions with a grain of salt.

- you need Node.js installed on the server, and MongoDB + Redis accessible
- the config instructions on the README were out of date - i fixed that
- see overriding config here; Mailsac uses the `node-config` module https://github.com/lorenwest/node-config/wiki
- the bash script `./install/ubuntu-14.04.sh` is a shell script for installing node, adding upstart and logrotate, and deploying the app from a local cloned version of this repository. It may serve as an example.
- you will need to create a database and user on mongodb, in order to setup a config setting to connect to it. this is not the case with redis.
