### ISSUE TITLE
Mailsac.com is down

### ISSUE THREAD

**Issue by Smile4ever** [ruffrey/mailsac#5]
Apache Test page is showing on mailsac.com, what's wrong?

**Comment by ruffrey** [comment]
mailsac 2.0 is up and the site should be working again.

I hope to release the core of mailsac 2 relatively soon. It has been rewritten from scratch and is much, much easier to setup.

**Comment by JokerQyou** [comment]
I was trying to set up mailsac on my own server yesterday but I found all the server links were hard-coded as `mailsac.com`, which was very confusing. And I figured out that the mailing functionality was normal, it looks like the repo's codes is somehow different with these used by `mailsac.com`. (Just guessing, because the UI differs very much)
And also I could not found license information about this repository. 
Finally I've found this issue :) . May I ask when will the codes of mailsac 2 be updated to this repo? I'm very interested in this project, because other mail server products like Postfix or sendmail are usually hard to configure, but this one is really easy.

**Comment by ruffrey** [comment]
Hey, I estimate only a handful of hours to finish the next version to the point of re-release. I just need to sit down and do it..
The license is MIT but it may not be in full text in the repo at the moment; sorry.
v2 is a complete rewrite btw. Though even less effort to stand it up (on Ubuntu or Debian).

via mobile

**Comment by JokerQyou** [comment]
Quick reply. Well, very glad to hear that, and looking forward to mailsac v2. Thx for this easy2use mail server. :)

**Comment by ruffrey** [comment]
For sure, it's been a fun and useful project. I should also note that there will be a plugin system. That's what is taking longer. It'll make it easier to add your own custom mail hooks (a little like Haraka but less sophisticated), and UI hooks.
