### ISSUE TITLE
Looking forward for mailsac v2

### ISSUE THREAD

**Issue by ttimasdf** [ruffrey/mailsac#6]
Before setting up, I was expecting to get a mail server looks the same with mailsac.com. But....err. Only the name looks familiar :-(

So, would there be a schedule to release the new mailsac core? Looking forward to it :-P

Regards,

**Comment by ruffrey** [comment]
Hi, man I would love to say I can commit to a schedule. Not gonna happen at the moment. Right now there are two blockers. 1 - extracting some of the payment stuff. 2 - troubleshooting an issue with `ECONNRESET` or `Error: socket hang up` that should be fixed with node 0.12, however other things break. If i can extract the payment stuff i'll probably release it anyways though.

**Comment by shkomg** [comment]
+1 on this

**Comment by ritvick** [comment]
+1 on this

**Comment by lifehome** [comment]
@ruffrey Sorry but what exactly is that "payment stuff"?

**Comment by ruffrey** [comment]
Hey, it pains me to see the last response I gave was Feb 25. damn sorry guys.
Payment stuff is that now you can pay for a little storage or private messages on mailsac.com, it almost keeps the lights on but still operates at a loss. i hacked it in there when rewriting the server and it needs to be modularized otherwise my paypal info is not just sitting in the open source project, heh. I have a branch with half-implemented plugin system IIRC
